### ISSUE TITLE
Enable "login with github" for CMS admin area

### ISSUE THREAD

**Issue by Levino** [hardforkio/homepage#218]
~~Currently we only support username / password but this dialogue is very shitty. For example lastpass does not recognize it as a password form. Lets use our github logins for this (Oauth)..~~ WONTFIX https://github.com/netlify/netlify-identity-widget/issues/86

**Comment by Bakkhos** [comment]
Done. I just had to enable the external OAuth provider Github in netlify CMS: 

![Selection_066](https://user-images.githubusercontent.com/93765/69325024-cbd37400-0c49-11ea-9f80-47926e723859.png)

I also enabled Google.

@Levino @EmceeEs I had to re-invite you. When you get the invite, click: "Continue with Github" or "Continue with google" instead of setting a password; after this point you should not need to enter any more passwords. Note "Continue with GitHub" will only work if the invited e-mail address is known to GitHub:

![Selection_067](https://user-images.githubusercontent.com/93765/69325243-253ba300-0c4a-11ea-9782-2ba851cf36d3.png)

**Comment by Bakkhos** [comment]
Closing as done (no code changes)

**Comment by Bakkhos** [comment]
Github and Gmail auth providers redirect you to hardfork.io instead of localhost or when editing normally; editing with localhost does not work except with email-password accounts

**Comment by kiliw** [comment]
This is still an open [issue](https://github.com/netlify/netlify-identity-widget/issues/86)

**Comment by Levino** [comment]
Okay. Wontfix. Please disable github login again and make sure that all devs still have an account.
